namespace DriveLinker.Core.Enums;

public enum Keyword
{
    Countdown,
    CreateADrive,
    Settings,
    Search,
    RecentlyAdded,
    DriveListing,
    LinkDrives,
    UnlinkDrives,
    Letter,
    LetterDesc,
    IpAddress,
    IpAddressDesc,
    DriveName,
    DriveNameDesc,
    Password,
    PasswordDesc,
    UserName,
    UserNameDesc,
    Create,
    AutoLinkDrives,
    AutoMinimize,
    Save,
    DateCreated,
    ClearOnlyLetterDriveName,
    Language,
    English,
    French,
    German,
    Indonesian,
}